### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
Someone opened an [RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1601) to get your app listed there. F-Droid highly recommends that summary & description are maintained in the app's repo (here) itself – so changes/updates/adjustments can be made by those knowing best, without the need of opening merge requests whenever that happens. Fastlane can be used with other "stores" as well, so it gives you "one place to rule them all".

You might wish to build on this (e.g. adding screenshots, a featureGraphic, per-release changelogs etc). For orientation, you might find my [Fastlane Cheat-Sheet](https://gitlab.com/snippets/1895688) useful.

PS: The format I've used for `full_description.txt` is what I call "Markdown lite", and has proven to work best when using different targets (like F-Droid, [my repo](https://apt.izzysoft.de/fdroid), Play Store). Some pointers on this can be found [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). It's quite simple, basically: separate paragraphs and lists by "empty lines", use "simple HTML" tags (b,i,u,a) where appropriate, avoid using headers (h1,h2,h3,..); that's all.

### CODE REVIEW

**Review by massivemadness — APPROVED** [review]
Hi, thanks for PR! I'm not familiar with fastlane yet, but the instruction you gave me looks great. I'll update the description later

**Comment by IzzySoft** [comment]
Thanks! And sure, whenever time permits. For now it's good to have it merged as-is (btw, taken from your app's listing in my repo). Please let me know when you've created the next tag (where fastlane then is available), so we can continue with the inclusion process at F-Droid.

**Comment by IzzySoft** [comment]
PS: also please let me know should you have added changelogs, screenshots, or a featureGraphic – as for my repo I need to enable that separately (for optimization to ensure good formatting).

**Comment by massivemadness** [comment]
@IzzySoft Yes, sure

**Comment by massivemadness** [comment]
@IzzySoft what's the specs for `images/icon.png`? Should it be a fully square like in google play, or should it be with rounded corners?

Снимок экрана 2021-01-16 в 12 44 37

**Comment by IzzySoft** [comment]
I'm not aware of any rules concerning that. Only that the aspect ration is 1:1 with an upper cap of 512x512 and a lower cap of 48x48. You could take a look at what most apps at F-Droid use if you're undecided. (checking) Urgs, that's undecided :rofl: about 50:50 as it looks like from the 1st page in alphabetical order… So: :man_shrugging: whatever you prefer it seems.

**Comment by massivemadness** [comment]
@IzzySoft I added screenshots and updated the description (it's on `master` now), what's the next steps? 🤔

**Comment by IzzySoft** [comment]
I see it's also tagged already (just the changelog was added too late for being used by F-Droid as you placed it *after* tagging – better first add the changelog, then tag).

The YAML for Brackey's metadata was already merged a week ago, so this new release will be picked up automatically – including the new screenshots, icon etc, just excluding the changelog (as it was added *after* tagging). So unless I've missed something, from your end all is done – thanks! I've just enabled featureGraphic for my repo, but have pulled the screenshots manually (I prefer the unframed ones, as especially on small screens they're giving better details – on bigger screens as well as they don't have that "light reflection").

Once your app shows up at F-Droid, after an "overlap" of about a week I usually remove it from my repo unless there's an explicit request to have it stay for some reason (some pros and cons are [listed here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ)). So now's the time to say so :wink:

**Comment by massivemadness** [comment]
@IzzySoft Hi Izzy!

My application `com.brackeys.ui` has been removed from Google Play due to copyright issues, so I've made some rebranding (new app name, repository url, new package name).

Could you please help me to apply these changes on FDroid and delete the previous app? Thank you

**Comment by IzzySoft** [comment]
I won't have much time the next few days – but what is it you need? Did you change the packageName (`com.brackeys.ui`) for the new version? Would it be an option to keep the old name on F-Droid? What kind of © must be cleaned up? Hard to help without details.

**Comment by IzzySoft** [comment]
I see. That would mean two MRs:

* introducing the new app (a different packageName means a different app)
* archiving the current one

The latter is easy (just apply `ArchivePolicy: 0 versions`). The former is not too difficult either: just take the current YAML file, copy it to the new package name, remove all but the latest build and adjust the remaining one to the first new build. Will you create the corresponding MRs, or do you wish that I do this for you?

**Comment by massivemadness** [comment]
@IzzySoft I'm not familiar with F-Droid gitlab, could you do that for me? 
And also, if I'll have questions in the future should I mention you here or somewhere else? 🤔

**Comment by IzzySoft** [comment]
See: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9064 (I'm not sure if the patch from the previous release still fits – if not, you'll have to provide a new one. Btw, if that happens on each release, it makes no sense having auto-update enabled as you'd need to manually add the patch anyway; it would be much better would you use a build flavor shipping without the patched-out stuff from the start).

As for "questions": if its general ones, rather open a ticket at the fitting place – it must not always be me personally (and TBH, I cannot be everywhere at the same time and answer everything :wink:) Else ping me from the fitting place – be it an issue here or at fdroiddata.

**Comment by IzzySoft** [comment]
As expected, the [patch failed](https://gitlab.com/IzzySoft/fdroiddata/-/jobs/1297433679#L2198). May I suggest that for now you provide a new (matching) patch – and for the next release you establish build flavors?

**Comment by massivemadness** [comment]
@IzzySoft Sure, I'll do that and then close https://github.com/massivemadness/Squircle-IDE/issues/38, thank you

**Comment by IzzySoft** [comment]
That'd be great – let's drop that patch right away and start with a clean new listing, thanks! Give me a ping when I can pick up again.

**Comment by IzzySoft** [comment]
Well, that issue has been closed. [My MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9064) still waits for the fix. Any news on that?

**Comment by massivemadness** [comment]
@IzzySoft I added the `fdroid` flavor in develop branch, but idk when will be the next release because I still got a lot of things to do :(

I think can simply cherry-pick these commits from develop to master and let you publish the app on fdroid

**Comment by IzzySoft** [comment]
> I think I'll simply cherry-pick these commits from develop to master

That would be helpful, thanks! And please drop me a note then when it was tagged, so I can pick up the MR again. Thanks in advance!

**Comment by massivemadness** [comment]
@IzzySoft It's on master branch now

**Comment by IzzySoft** [comment]
Thanks! Good news on the [F-Droid replace MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9064) as well: we got the build fixed for the rebranded one, making the patch obsolete – will be merged in a few minutes (once the CI build succeeds I'll rebase and merge). Note the warning from our scanner, though:

> `name` in `de` should be shorter than 50 characters!

That means the `title.txt`. It will be truncated to 50 chars now, so maybe you'll adjust it for the next release? As all apps in F-Droid are free and for Android, I'd suggest to remove the obvious parts and change from "Squircle IDE - ein schneller und freier Code-Editor für Android" to "Squircle IDE - ein schneller Code-Editor".

**Comment by massivemadness** [comment]
@IzzySoft Sure, I'll change it in the next release. Thank you

**Comment by IzzySoft** [comment]
Rebase in process now, set to merge when succeeded \o/ Please give me a ping when it's time to archive the predecessor.

**Comment by IzzySoft** [comment]
Merged! The next build cycle (the current one just started this morning) should pick it up, so expect the changes to have effect in about a week.

**Comment by massivemadness** [comment]
@IzzySoft Awesome, you can remove the previous app if you didn't already

**Comment by IzzySoft** [comment]
I wouldn't do that before the new one is live, but immediately thereafter. So should I forget, please remind me.

**Pull request merged**
